In [1]:
!pip install pandas regex

Requirement already satisfied: pandas in c:\users\aayush\anaconda3\envs\objdet\lib\site-packages (1.0.3)
Requirement already satisfied: regex in c:\users\aayush\anaconda3\envs\objdet\lib\site-packages (2020.5.7)
Requirement already satisfied: pytz>=2017.2 in c:\users\aayush\anaconda3\envs\objdet\lib\site-packages (from pandas) (2019.3)
Requirement already satisfied: python-dateutil>=2.6.1 in c:\users\aayush\anaconda3\envs\objdet\lib\site-packages (from pandas) (2.8.1)
Requirement already satisfied: numpy>=1.13.3 in c:\users\aayush\anaconda3\envs\objdet\lib\site-packages (from pandas) (1.18.1)
Requirement already satisfied: six>=1.5 in c:\users\aayush\anaconda3\envs\objdet\lib\site-packages (from python-dateutil>=2.6.1->pandas) (1.14.0)

In [2]:
import pandas as pd 
import re

Using Regular Expression To Identify The Roll Number

In [3]:
regex = re.compile('(TC\s+\d{3}?)|(TC\d{3}?)|(TC-\d{3})',re.IGNORECASE)

In [4]:
# Reading the Chat File replace the 'lecture.txt' with the file name
#make sure the file is in the same folder as this script or enter the whole path for the file

text = ""
for words in open('ChatFile.txt'):
    text += words

In [5]:
#The text from the file as a string 
text

'00:00:03.134,00:00:06.134\nsomeshwar marepalle: Someshwar Marepalle TC164\n\n00:00:07.135,00:00:10.135\nshlok karandikar: Shlok Karandikar TC223\n\n00:00:21.293,00:00:24.293\nswarali degaonkar: Swarali Degaonkar TC114\n\n00:00:36.447,00:00:39.447\nShubham Pawale: Shubham Pawale TC152\n\n00:01:15.487,00:01:18.487\nsameeksha joshi: Sameeksha Joshi TC 179 \n\n00:01:17.915,00:01:20.915\nsnehal vipradas: Snehal Vipradas TC264\n\n00:01:19.039,00:01:22.039\npranjali kulkarni: Pranjali Kulkarni TC269\n\n00:01:37.377,00:01:40.377\nom mokashi: Om Mokashi TC143\n\n00:02:16.858,00:02:19.858\nshreya patki: Shreya Patki TC248\n\n00:02:19.505,00:02:22.505\napurva upasani: Apurva Upasani TC265\n\n00:02:23.895,00:02:26.895\ndhairyasheel jagtap: Dhairyasheel Jagtap TC219\n\n00:02:27.068,00:02:30.068\nrohan hingane: Rohan Hingane TC217\n\n00:02:28.101,00:02:31.101\ndnyanesh mahajan: Dnyanesh Mahajan TC232\n\n00:02:30.415,00:02:33.415\ndarshan galakatu: darshan galakatu TC117\n\n00:02:34.024,00:02:37.024\ndevashish shahakar: Devashish Dilip Shahakar\nTC220\n\n00:02:40.927,00:02:43.927\nkaivalya joshi: Kaivalya Joshi TC126\n\n00:02:41.761,00:02:44.761\nkeerthi g: Keerthi Nagaraj G TC144\n\n00:02:46.086,00:02:49.086\nanushka bangal: Security\n\n00:02:52.745,00:02:55.745\naditya pansare: Aditya Pansare TC166\n\n00:02:53.000,00:02:56.000\nsai yerunkar: Sai Yerunkar TC161\n\n00:02:54.709,00:02:57.709\nNeha Pande: Neha pande TC146\n\n00:03:00.651,00:03:03.651\naishwarya pardeshi: Pardeshi Aishwarya TC149\n\n00:03:09.962,00:03:12.962\nshubham chavan: Shubham Chavan TC111\n\n00:03:31.428,00:03:34.428\nmanasi khillare: Manasi Khillare TC131\n\n00:03:31.707,00:03:34.707\ngauri markandey: Gauri Markandey TC139\n\n00:05:26.836,00:05:29.836\nsourabh gharad: Sourabh gharad TC119\n\n00:05:30.020,00:05:33.020\napoorva bhadbhade: Apoorva Bhadbhade TC109\n\n00:09:29.612,00:09:32.612\nAKSHADA PHALLE: Akshada phalle TC262\n\n00:09:34.223,00:09:37.223\nprasad lahamage: Prasad Lahamage TC231\n\n00:09:43.283,00:09:46.283\npriyansh bafna: Priyansh Bafna TC105\n\n00:11:36.203,00:11:39.203\nDhiraj Pagar: Dhiraj Pagar\nTC 145\n\n00:11:36.274,00:11:39.274\nsrishti adkar: Srishti Adkar TC101\n\n00:11:51.168,00:11:54.168\nyukta patil: Yukta Patil TC247\n\n00:12:20.228,00:12:23.228\nDhiraj Pagar: Dhiraj Pagar\nTC 145\n\n00:13:17.394,00:13:20.394\nrutwik wanve: Rutwik Wanve TC258\n\n00:13:34.811,00:13:37.811\nbhavika karale: Bhavika Karale TC 178\n\n00:18:03.558,00:18:06.558\nmrunali dasari: TC 211\n\n\n00:18:03.558,00:18:06.558\nAayush Gavande: TC-118\n\n'

In [6]:
#getting the roll number using the regular expression 

roll = regex.findall(text)

In [7]:
#list of roll numbers found from the text
roll

[('', 'TC164', ''),
 ('', 'TC223', ''),
 ('', 'TC114', ''),
 ('', 'TC152', ''),
 ('TC 179', '', ''),
 ('', 'TC264', ''),
 ('', 'TC269', ''),
 ('', 'TC143', ''),
 ('', 'TC248', ''),
 ('', 'TC265', ''),
 ('', 'TC219', ''),
 ('', 'TC217', ''),
 ('', 'TC232', ''),
 ('', 'TC117', ''),
 ('', 'TC220', ''),
 ('', 'TC126', ''),
 ('', 'TC144', ''),
 ('', 'TC166', ''),
 ('', 'TC161', ''),
 ('', 'TC146', ''),
 ('', 'TC149', ''),
 ('', 'TC111', ''),
 ('', 'TC131', ''),
 ('', 'TC139', ''),
 ('', 'TC119', ''),
 ('', 'TC109', ''),
 ('', 'TC262', ''),
 ('', 'TC231', ''),
 ('', 'TC105', ''),
 ('TC 145', '', ''),
 ('', 'TC101', ''),
 ('', 'TC247', ''),
 ('TC 145', '', ''),
 ('', 'TC258', ''),
 ('TC 178', '', ''),
 ('TC 211', '', ''),
 ('', '', 'TC-118')]

In [8]:
#Loading the rollcall list using pandas 

Attendance_df = pd.read_csv('Roll_List.csv')

In [9]:
Attendance_df

   Roll No.            Name of Student
0     TC101     ADKAR SRISHTI SADANAND
1     TC102        AKBAR AADIL ADHEESH
2     TC103  AMANGI AISHWARYA RAJENDRA
3     TC104              ANJALI KUMARI
4     TC105     BAFNA PRIYANSH AASHISH
..      ...                        ...
64    TC170           DOMBALE JAYASHRI
65    TC171            BHOSALE SIDDESH
66    TC172          KULKARNI PRANJALI
67    TC173               YADAV PRAMOD
68    TC174              HIWALE DIKSHA

[69 rows x 2 columns]

In [10]:
#Adding a new columns attendance and adding everyone as absent

Attendance_df['Attendance'] = 'Absent'
Attendance_df

   Roll No.            Name of Student Attendance
0     TC101     ADKAR SRISHTI SADANAND     Absent
1     TC102        AKBAR AADIL ADHEESH     Absent
2     TC103  AMANGI AISHWARYA RAJENDRA     Absent
3     TC104              ANJALI KUMARI     Absent
4     TC105     BAFNA PRIYANSH AASHISH     Absent
..      ...                        ...        ...
64    TC170           DOMBALE JAYASHRI     Absent
65    TC171            BHOSALE SIDDESH     Absent
66    TC172          KULKARNI PRANJALI     Absent
67    TC173               YADAV PRAMOD     Absent
68    TC174              HIWALE DIKSHA     Absent

[69 rows x 3 columns]

In [11]:
for i in range(0,len(roll)):
    for j in range(0,len(Attendance_df)):
        if(Attendance_df['Roll No.'][j] == roll[i][1] or Attendance_df['Roll No.'][j] == roll[i][0].replace(" ","") or Attendance_df['Roll No.'][j] == roll[i][2].replace("-","")):
            Attendance_df['Attendance'][j] = "Present"

In [12]:
# Looking at the attendance sheet 
Attendance_df.head(50)

   Roll No.              Name of Student Attendance
0     TC101       ADKAR SRISHTI SADANAND    Present
1     TC102          AKBAR AADIL ADHEESH     Absent
2     TC103    AMANGI AISHWARYA RAJENDRA     Absent
3     TC104                ANJALI KUMARI     Absent
4     TC105       BAFNA PRIYANSH AASHISH    Present
5     TC106   BAIRAGI DEVENDRA GHANSHYAM     Absent
6     TC107       BANGAL ANUSHKA SANDEEP     Absent
7     TC108        BAPAT ATHARVA VAIBHAV     Absent
8     TC109    BHADBHADE APOORVA SANDEEP    Present
9     TC110      BORHADE RAVIRAJ GAVNATH     Absent
10    TC111               CHAVAN SHUBHAM    Present
11    TC112   CHILVERY SANSKRUTI SANTOSH     Absent
12    TC113   DAHIBHATE MAYUR DATTATRAYA     Absent
13    TC114  DEGAONKAR SWARALI MORESHWAR    Present
14    TC115       DHAPARE SAHIL SOURABHA     Absent
15    TC116        GAIKWAD ADITI PRAKASH     Absent
16    TC117     GALAKATU DARSHAN BHUSHAN    Present
17    TC118       GAVANDE AAYUSH AVINASH    Present
18    TC119        GHARAD SOURABH BHARAT    Present
19    TC120    GODBOLE PRIYANKA RAJENDRA     Absent
20    TC121      HUDDAR MRUDULA SADANAND     Absent
21    TC122       INGOLE DIGVIJAY SANJAY     Absent
22    TC123           JADHAV SUJIT MANOJ     Absent
23    TC124        JAGTAP SHANTANU SUNIL     Absent
24    TC125              JAIN SAHIL RAJU     Absent
25    TC126     JOSHI KAIWALYA DHANANJAY    Present
26    TC128    KATDARE ARATI BALAKRISHNA     Absent
27    TC129          KELKAR ADVAIT PARAG     Absent
28    TC130           KERKAR KETKI SUNIL     Absent
29    TC131      KHILLARE MANASI SUBHASH    Present
30    TC133        KULKARNI RUTUJA SUHAS     Absent
31    TC134    KURUMKAR PRANALI RAJENDRA     Absent
32    TC135   MAHAGAONKAR CHINMAY NILESH     Absent
33    TC136     MAHAJAN AISHWARYA HEMANT     Absent
34    TC137       MAHAJAN SANDESH RAJESH     Absent
35    TC138      MALUSARE HRUCHA VITTHAL     Absent
36    TC139       MARKANDEY GAURI SANJAY    Present
37    TC140        MASKE PREETAM AVINASH     Absent
38    TC142      MOHARIR SHAUNAK SHEKHAR     Absent
39    TC143          MOKASHI OM RAJENDRA    Present
40    TC144            NAGARAJ G KEERTHI    Present
41    TC145          PAGAR DHIRAJ SANJAY    Present
42    TC146            PANDE NEHA SANJAY    Present
43    TC147         PANDIT TEJAS VAIBHAV     Absent
44    TC148      PARDESHI ADITYA PRAKASH     Absent
45    TC149    PARDESHI AISHWARYA SURESH    Present
46    TC150          PATIL AMIT ANANTRAO     Absent
47    TC151        PATIL PRAMOD RAJENDRA     Absent
48    TC152         PAWALE SHUBHAM RAJU     Present
49    TC153          PHADNIS VINAY VIVEK     Absent

In [13]:
Attendance_df['Attendance'].value_counts()

Absent     49
Present    20
Name: Attendance, dtype: int64

In [14]:
Attendance_df.to_csv('Attendance.csv',index=False) # Saving it to a file named attendance.csv